server:
  port: 8093
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/sbintervention
    username: { DB_USERNAME }
    password: { DB_PASSWORD }
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "init"
    locations: classpath:db/migration
