server:
  port: 8092
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
spring:
  application:
    name: listing-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/sblisting
    username: oussema
    password: oussema
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "init"
    locations: classpath:db/migration
