
    create table applications (
        id bigint generated by default as identity,
        listing_id bigint,
        technician_id bigint,
        message varchar(255),
        status varchar(255) check (status in ('PENDING','ACCEPTED','REJECTED')),
        primary key (id)
    );

    create table categories (
        id bigint generated by default as identity,
        parent_id bigint,
        description varchar(255),
        icon_code varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table listings (
        customer_id bigint,
        id bigint generated by default as identity,
        description TEXT,
        status varchar(255) check (status in ('DRAFT','ACTIVE','FILLED','ARCHIVED')),
        title varchar(255),
        primary key (id)
    );

    create table listings_categories (
        category_id bigint not null,
        listing_id bigint not null,
        primary key (category_id, listing_id)
    );

    alter table if exists applications 
       add constraint FKi4g6854kul57088gaiiq1u5o7 
       foreign key (listing_id) 
       references listings;

    alter table if exists categories 
       add constraint FKsaok720gsu4u2wrgbk10b5n8d 
       foreign key (parent_id) 
       references categories;

    alter table if exists listings_categories 
       add constraint FKm2n6x396nhvixf82cvyrthq72 
       foreign key (category_id) 
       references categories;

    alter table if exists listings_categories 
       add constraint FKhus5a6xg092ww4crfdge3n17t 
       foreign key (listing_id) 
       references listings;

    create table applications (
        id bigint generated by default as identity,
        listing_id bigint,
        technician_id bigint,
        message varchar(255),
        status varchar(255) check (status in ('PENDING','ACCEPTED','REJECTED')),
        primary key (id)
    );

    create table categories (
        id bigint generated by default as identity,
        parent_id bigint,
        description varchar(255),
        icon_code varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table listings (
        customer_id bigint,
        id bigint generated by default as identity,
        description TEXT,
        status varchar(255) check (status in ('DRAFT','ACTIVE','FILLED','ARCHIVED')),
        title varchar(255),
        primary key (id)
    );

    create table listings_categories (
        category_id bigint not null,
        listing_id bigint not null,
        primary key (category_id, listing_id)
    );

    alter table if exists applications 
       add constraint FKi4g6854kul57088gaiiq1u5o7 
       foreign key (listing_id) 
       references listings;

    alter table if exists categories 
       add constraint FKsaok720gsu4u2wrgbk10b5n8d 
       foreign key (parent_id) 
       references categories;

    alter table if exists listings_categories 
       add constraint FKm2n6x396nhvixf82cvyrthq72 
       foreign key (category_id) 
       references categories;

    alter table if exists listings_categories 
       add constraint FKhus5a6xg092ww4crfdge3n17t 
       foreign key (listing_id) 
       references listings;

    create table applications (
        id bigint generated by default as identity,
        listing_id bigint,
        technician_id bigint,
        message varchar(255),
        status varchar(255) check (status in ('PENDING','ACCEPTED','REJECTED')),
        primary key (id)
    );

    create table categories (
        id bigint generated by default as identity,
        parent_id bigint,
        description varchar(255),
        icon_code varchar(255),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table listings (
        customer_id bigint,
        id bigint generated by default as identity,
        description TEXT,
        status varchar(255) check (status in ('DRAFT','ACTIVE','FILLED','ARCHIVED')),
        title varchar(255),
        primary key (id)
    );

    create table listings_categories (
        category_id bigint not null,
        listing_id bigint not null,
        primary key (category_id, listing_id)
    );

    alter table if exists applications 
       add constraint FKi4g6854kul57088gaiiq1u5o7 
       foreign key (listing_id) 
       references listings;

    alter table if exists categories 
       add constraint FKsaok720gsu4u2wrgbk10b5n8d 
       foreign key (parent_id) 
       references categories;

    alter table if exists listings_categories 
       add constraint FKm2n6x396nhvixf82cvyrthq72 
       foreign key (category_id) 
       references categories;

    alter table if exists listings_categories 
       add constraint FKhus5a6xg092ww4crfdge3n17t 
       foreign key (listing_id) 
       references listings;
